version: "3.7"

services:
  front:
    image: twutter-front:latest
    build:
      context: front
    restart: always
    ports:
      - "80:5000"

  back:
    image: twutter-back:latest
    build:
      context: back
    restart: always
    environment:
      PORT: 5000
    ports:
      - "5000:5000"
    links:
      - mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo:3.7
    restart: always
    container_name: mongodb
    ports:
      - 27017
